version: '3'

volumes:
  pg_data_production:
  backend_static_volume:
  frontend_static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: norugin/foodgram_backend
    env_file: .env
    volumes:
      - backend_static_volume:/backend_static/static_backend
      - media_volume:/app/media
  frontend:
    image: norugin/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static_volume:/frontend_static/
  nginx:
    image: norugin/gateway
    env_file: .env
    ports:
      - 80:80
    volumes:
      - backend_static_volume:/backend_static
      - frontend_static_volume:/frontend_static/
      - media_volume:/app/media
